version: "3.3"
services:
    basededades:
        image: mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: dbP9
            MYSQL_PASSWORD: contrasenya
            MYSQL_USER: usuarioP9
            MYSQL_ROOT_PASSWORD: contrasenyaP9
        volumes:
            - mivolumen:/var/lib/mysql
        networks:
            - default
    www1:
        build: .
        ports: 
            - "81:80"
        volumes:
            - /home/admin/web1:/var/www/html
        links:
            - basededades
        networks:
            - default

    www2:
        build: .
        ports: 
            - "82:80"
        volumes:
            - /home/admin/web2:/var/www/html
        links:
            - basededades
        networks:
            - default

    www3:
        build: .
        ports: 
            - "83:80"
        volumes:
            - /home/admin/web3:/var/www/html
        links:
            - basededades
        networks:
            - default
 
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - basededades:db
        ports:
            - 84:80
volumes:
    mivolumen:

